fastlane_version '2.219.0'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan()
    end

    desc 'Test build'
    lane :tests do
    	run_tests()
    end


end