fastlane_version '2.219.0'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
        workspace: "Construction Helper.xcworkspace",
        scheme: "Construction Helper",
        devices: ["iPhone 13 mini"],
        clean: true
      )
    end
end