fastlane_version '2.219.0'
default_platform :ios

platform :ios do
	desc 'Install pods'
	lane :install_pods do
		cocoapods(
	    	clean: true,
	    	podfile: "./Podfile",
	    	try_repo_update_on_error: true,
	    	use_bundle_exec: false
	    )
	end

    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
      	workspace: "Construction Helper.xcodeproj/project.xcworkspace"
      )
    end

    desc 'Testing XCTest'
    lane :test do
    xctest()
  end

end