name: iOS_Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1.172.0

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Install Dependencies
        run: pod install

      - name: Run Tests
        run: bundle exec fastlane unit_test
