name: On Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: SwiftTest by SwiftActions
      - uses: SwiftActions/SwiftTest@0.2
